version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: domino
      POSTGRES_DB: dbdj
      POSTGRES_USER: domino
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
 
volumes:
  db-data:
  
